before_script:
    - date

cache:
    untracked: true
    key:
        files:
            - backend/requirements.txt
            - frontend/package.json
    when: on_failure
    paths:
    - frontend/node_modules/
    - frontend/.yarn/
    - backend/localvenv/

frontend:
    image: node:14.16.0
    script:
    - ls -al
    - cd frontend
    - if [[ ! -d "node_modules" ]]; then 
        yarn install --cache-folder .yarn;
        echo "Pipeline dependencies have been reinstalled, please retry"; 
        exit 1; 
      fi
    - yarn install --cache-folder .yarn --frozen-lockfile
    - yarn lint
    - yarn test

backend:
    image: python:3.7
    script:
    - ls -al
    - cd backend
    - if [[ ! -d "localvenv" ]]; then
        python3 -m venv localvenv;
        source localvenv/bin/activate;
        pip install -r requirements.txt;
        echo "Pipeline dependencies have been reinstalled, please retry"; 
        exit 1; 
      fi
    - source localvenv/bin/activate
    - pytest