before_script:
    - date

cache:
    key: tpm-key
    paths:
    - node_modules/
    - .yarn

frontend:
    image: node:14.16.0
    script:
    - ls -al
    - cd frontend
    - yarn install --cache-folder .yarn
    - yarn build
    - yarn test