before_script:
    - date

cache:
    untracked: true
    key:
        files:
            - backend/requirements.txt
            - frontend/package.json
    when: on_failure
    paths:
    - frontend/node_modules/
    - frontend/.yarn/
    - backend/localvenv/

frontend:
    image: node:14.16.0
    script:
    - cd frontend
    - ls -al
    - if [[ ! -d "node_modules" ]]; then 
        yarn install --cache-folder .yarn;
        echo "Pipeline dependencies have been reinstalled, please retry"; 
        exit 1; 
      fi
    - yarn install --cache-folder .yarn --frozen-lockfile
    - yarn lint
    - yarn test --verbose

postman:
    image: node:14.16.0
    script:
    - npm install -g newman
    - newman --version
    - newman run Postman.json

backend:
    image: python:3.7
    script:
    - cd backend
    - ls -al
    - if [[ ! -d "localvenv" ]]; then
        python3 -m venv localvenv;
        source localvenv/bin/activate;
        pip install -r requirements.txt;
        echo "Pipeline dependencies have been reinstalled, please retry"; 
        exit 1; 
      fi
    - source localvenv/bin/activate
    - pytest -v

gui_tests:
    image: python:3.9.4
    script:
    - pip install selenium
    - wget https://chromedriver.storage.googleapis.com/89.0.4389.23/chromedriver_linux64.zip
    - unzip chromedriver_linux64.zip
    - mv chromedriver /usr/bin/chromedriver
    - chown root:root /usr/bin/chromedriver
    - chmod +x /usr/bin/chromedriver
    - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
    - sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
    - apt-get update -qy && apt-get install -y google-chrome-stable
    - cd frontend
    - python3 guitests.py