before_script:
    - date

cache:
    untracked: true
    key: tpm-key
    paths:
    - frontend/node_modules/
    - frontend/.yarn/

frontend:
    image: node:14.16.0
    script:
    - ls -al
    - cd frontend
    - yarn install --cache-folder .yarn
    - yarn build
    - yarn test