before_script:
    - date

cache:
    untracked: true
    key:
        files:
            - frontend/yarn.lock
            - frontend/package.json
    paths:
    - frontend/node_modules/
    - frontend/.yarn/

frontend:
    image: node:14.16.0
    script:
    - ls -al
    - cd frontend
    - yarn install --cache-folder .yarn --frozen-lockfile
    - yarn build
    - yarn test